import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faCheckCircle,
  faClock,
  faBolt,
  faLightbulb,
  faDollarSign,
  faComment,
  faQuestionCircle,
  faKey,
  faSync,
  faImage,
  faPaperPlane,
  faRedo,
  faHatWizard,
  faEnvelope,
  faBars,
  faBell,
  faCog,
  faShoppingBasket,
  faUpDown,
  faUserAstronaut,
  faRightToBracket,
  faEye,
  faEyeSlash,
  faHardDrive,
  faTimes,
  faPhone,
  faLock,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight
} from '@fortawesome/free-solid-svg-icons'

import { faTelegram } from '@fortawesome/free-brands-svg-icons'

library.add(
  faCheckCircle,
  faClock,
  faBolt,
  faLightbulb,
  faDollarSign,
  faComment,
  faQuestionCircle,
  faKey,
  faSync,
  faImage,
  faPaperPlane,
  faRedo,
  faHatWizard,
  faEnvelope,
  faTelegram,
  faBars,
  faBell,
  faCog,
  faShoppingBasket,
  faUpDown,
  faUserAstronaut,
  faRightToBracket,
  faEye,
  faEyeSlash,
  faHardDrive,
  faTimes,
  faPhone,
  faLock,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight
)

export { FontAwesomeIcon }
